_wandb:
    value:
        cli_version: 0.26.1
        e:
            hi6j3rcj805z12vam8nxpmcz3o59jrnb:
                apple: {}
                cpu_count: 18
                cpu_count_logical: 18
                disk:
                    /:
                        total: "994610155520"
                        used: "183756599296"
                email: singhh5050@gmail.com
                executable: /Library/Developer/CommandLineTools/usr/bin/python3
                git:
                    commit: 3cbcaae569336ad203a518c3443afbdeb334e209
                    remote: https://github.com/singhh5050/delta-attention.git
                host: H766QV2N26
                memory:
                    total: "51539607552"
                os: macOS-26.5.1-arm64-arm-64bit
                program: <stdin>
                python: CPython 3.9.6
                root: /Users/harshvardhan@nvidia.com/Development/delta-attention/repo
                startedAt: "2026-07-16T00:03:37.358146Z"
                writerId: hi6j3rcj805z12vam8nxpmcz3o59jrnb
        m: []
        python_version: 3.9.6
        t:
            "1":
                - 49
            "2":
                - 49
            "3":
                - 2
                - 13
            "4": 3.9.6
            "5": 0.26.1
            "12": 0.26.1
            "13": darwin-arm64
